In [25]:
from FixturesOdds import FixturesOdds
%load_ext autoreload 
%autoreload 2
import requests
import pandas as pd

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [76]:
fix_pred=FixturesOdds()

In [77]:
fix_pred.get_odds('ladbrokes',1)

KeyError: 'data'

In [108]:
    def xx(bookie_key, leaugeid):
        
        apiKey='fc3fa79ee130aa6427d2d86743b794fc'
        apiKey = 'edddec034215860d93d49887ede78024'
        sports = {1 : 'soccer_epl', 2: 'soccer_efl_champ'}
        sport = sports[leaugeid]
        url = "https://api.the-odds-api.com/v3/odds/?sport=%s&region=uk&apiKey=%s" % (sport,apiKey)

        #url="https://api.the-odds-api.com/v3/odds/?sport=soccer_epl&region=uk&apiKey=fc3fa79ee130aa6427d2d86743b794fc"
        r = requests.get(url=url)
        json=r.json()
        games = json['data']

        home_teams = [game['home_team'] for game in games]
        sites = [game['sites'] for game in games]
        odds=[s['odds']['h2h'] for site in sites for s in site if s['site_key']==bookie_key]
        
        first_team = [game['teams'][0] for game in games]
        x =  list(zip(home_teams,odds,first_team))
        
        df1=pd.DataFrame(x)
        
        df1[['HomeOdds', 'AwayOdds', 'DrawOdds']]=pd.DataFrame(df1[1].values.tolist(), index=df1.index)
        df1=df1[[0,1,2,'HomeOdds', 'DrawOdds', 'AwayOdds']].apply(swap,1)
        df1.replace({'Bournemouth' : 'AFC Bournemouth'}, inplace=True)
        df1.rename(columns={0:'HomeTeam'}, inplace=True)
        return df1[['HomeTeam','HomeOdds', 'DrawOdds', 'AwayOdds']]
        
#        df1.replace({'Bournemouth' : 'AFC Bournemouth'}, inplace=True)
#        df1.rename(columns={0:'HomeTeam'}, inplace=True)
        
#        return df1 #[['HomeTeam','HomeOdds', 'DrawOdds', 'AwayOdds']]

In [113]:
d=xx('ladbrokes',2)
d

               HomeTeam  HomeOdds  DrawOdds  AwayOdds
0   Sheffield Wednesday      3.40      3.20      2.20
1      Blackburn Rovers      3.25      3.30      2.20
2        Wigan Athletic      3.10      3.50      2.20
3            Stoke City      2.00      3.20      4.00
4             Brentford      1.75      3.70      4.50
5               Reading      2.75      3.10      2.60
6             Hull City      2.65      3.30      2.60
7      Rotherham United      2.20      3.20      3.40
8           Aston Villa      1.87      3.50      4.20
9          Ipswich Town      2.65      3.10      2.75
10    Nottingham Forest      2.30      3.25      3.10
11         Derby County      2.55      3.30      2.70
12         Norwich City      2.38      3.20      3.00
13             Millwall      2.20      3.20      3.40
14         Swansea City      2.20      3.20      3.30
15        Middlesbrough      1.00       NaN      1.00
16  Queens Park Rangers      1.91      3.40      4.20
17     Sheffield United      2.30      3.30      3.00
18      Birmingham City      1.80      3.50      4.60
19              Preston      1.44      4.25      7.50
20         Bristol City      1.00       NaN      1.00
21         Leeds United      1.95      3.40      3.80

                    HomeTeam  HomeOdds DrawOdds  AwayOdds
0                    Chelsea      1.70      3.8      5.00
1               Cardiff City      2.40      3.3      2.80
2           Newcastle United      2.15        b      3.70
3            AFC Bournemouth      2.00      3.5      3.60
4            Manchester City      1.07        b     34.00
5    Wolverhampton Wanderers      1.73        b      5.00
6            West Ham United      4.00        b      1.80
7          Huddersfield Town     12.00        5      1.30
8                    Everton      1.83        b      4.33
9                    Arsenal      1.53     4.33      5.75
10               Southampton      2.15        b      3.50
11                 Liverpool      1.09        b     34.00
12                    Fulham      2.65        b      2.45
13  Brighton and Hove Albion      3.10      3.1      2.40
14                   Watford      1.75        b      4.80
15            Leicester City      1.83      3.7      4.00
16            Crystal Palace      1.67        b      5.20
17                   Burnley      1.83     3.75      4.00

In [97]:
d.replace({'Bournemouth' : 'AFC Bournemouth'}, inplace=True)
d.rename(columns={0:'HomeTeam'}, inplace=True)
d[['HomeTeam','HomeOdds', 'DrawOdds', 'AwayOdds']]

                    HomeTeam  HomeOdds  DrawOdds  AwayOdds
0                    Chelsea      1.70      3.80      5.00
1               Cardiff City      2.40      3.30      2.80
2           Newcastle United      3.60      3.10      2.15
3            AFC Bournemouth      2.00      3.50      3.60
4            Manchester City     34.00     13.00      1.07
5    Wolverhampton Wanderers      5.00      3.50      1.73
6            West Ham United      1.80      3.50      4.00
7          Huddersfield Town     12.00      5.00      1.30
8                    Everton      4.33      3.50      1.83
9                    Arsenal      1.53      4.33      5.75
10               Southampton      3.50      3.20      2.15
11                 Liverpool     34.00     10.00      1.09
12                    Fulham      2.45      3.60      2.65
13  Brighton and Hove Albion      3.10      3.10      2.40
14                   Watford      4.80      3.40      1.75
15            Leicester City      1.83      3.70      4.00
16            Crystal Palace      5.20      3.75      1.67
17                   Burnley      1.83      3.75      4.00

In [87]:
d[[0,1,2,'HomeOdds', 'DrawOdds', 'AwayOdds']]

,0,1,2,HomeOdds,DrawOdds,AwayOdds
0,Chelsea,"[1.7, 5, 3.8]",Chelsea,1.70,3.80,5.00
1,Cardiff City,"[2.4, 2.8, 3.3]",Cardiff City,2.40,3.30,2.80
2,Newcastle United,"[3.6, 2.15, 3.1]",Brighton and Hove Albion,2.15,3.10,3.60
3,Bournemouth,"[2, 3.6, 3.5]",Bournemouth,2.00,3.50,3.60
4,Manchester City,"[34, 1.07, 13]",Burnley,1.07,13.00,34.00
5,Wolverhampton Wanderers,"[5, 1.73, 3.5]",Watford,1.73,3.50,5.00
6,West Ham United,"[1.8, 4, 3.5]",Tottenham Hotspur,4.00,3.50,1.80
7,Huddersfield Town,"[12, 1.3, 5]",Huddersfield Town,12.00,5.00,1.30
8,Everton,"[4.33, 1.83, 3.5]",Crystal Palace,1.83,3.50,4.33
9,Arsenal,"[1.53, 5.75, 4.33]",Arsenal,1.53,4.33,5.75
10,Southampton,"[3.5, 2.15, 3.2]",Newcastle United,2.15,3.20,3.50
11,Liverpool,"[34, 1.09, 10]",Cardiff City,1.09,10.00,34.00
12,Fulham,"[2.45, 2.65, 3.6]",Bournemouth,2.65,3.60,2.45
13,Brighton and Hove Albion,"[3.1, 2.4, 3.1]",Brighton and Hove Albion,3.10,3.10,2.40
14,Watford,"[4.8, 1.75, 3.4]",Huddersfield Town,1.75,3.40,4.80
15,Leicester City,"[1.83, 4, 3.7]",Leicester City,1.83,3.70,4.00
16,Crystal Palace,"[5.2, 1.67, 3.75]",Arsenal,1.67,3.75,5.20
17,Burnley,"[1.83, 4, 3.75]",Burnley,1.83,3.75,4.00

In [80]:
saved_away=d['AwayOdds']
swapindex=d[0]!=d[2] # if the home team is wrong
d.loc[swapindex, 'AwayOdds']=d['HomeOdds'] 
d.loc[swapindex, 'HomeOdds']=saved_away
d

,0,1,2,HomeOdds,AwayOdds,DrawOdds
0,Chelsea,"[1.7, 5, 3.8]",Chelsea,1.70,5.00,3.80
1,Cardiff City,"[2.4, 2.8, 3.3]",Cardiff City,2.40,2.80,3.30
2,Newcastle United,"[3.6, 2.15, 3.1]",Brighton and Hove Albion,2.15,3.60,3.10
3,Bournemouth,"[2, 3.6, 3.5]",Bournemouth,2.00,3.60,3.50
4,Manchester City,"[34, 1.07, 13]",Burnley,1.07,34.00,13.00
5,Wolverhampton Wanderers,"[5, 1.73, 3.5]",Watford,1.73,5.00,3.50
6,West Ham United,"[1.8, 4, 3.5]",Tottenham Hotspur,4.00,1.80,3.50
7,Huddersfield Town,"[12, 1.3, 5]",Huddersfield Town,12.00,1.30,5.00
8,Everton,"[4.33, 1.83, 3.5]",Crystal Palace,1.83,4.33,3.50
9,Arsenal,"[1.53, 5.75, 4.33]",Arsenal,1.53,5.75,4.33
10,Southampton,"[3.5, 2.15, 3.2]",Newcastle United,2.15,3.50,3.20
11,Liverpool,"[34, 1.09, 10]",Cardiff City,1.09,34.00,10.00
12,Fulham,"[2.45, 2.65, 3.6]",Bournemouth,2.65,2.45,3.60
13,Brighton and Hove Albion,"[3.1, 2.4, 3.1]",Brighton and Hove Albion,3.10,2.40,3.10
14,Watford,"[4.8, 1.75, 3.4]",Huddersfield Town,1.75,4.80,3.40
15,Leicester City,"[1.83, 4, 3.7]",Leicester City,1.83,4.00,3.70
16,Crystal Palace,"[5.2, 1.67, 3.75]",Arsenal,1.67,5.20,3.75
17,Burnley,"[1.83, 4, 3.75]",Burnley,1.83,4.00,3.75

In [110]:
def swap (row):
    if row[0]!= row[2]:
        return[row[0], row[1],row[2],row['AwayOdds'], row['DrawOdds'], row['HomeOdds']]
    else:
        return[row[0], row[1],row[2],row['HomeOdds'], row['DrawOdds'], row['AwayOdds']]

In [62]:
dict1=[{0:'Chelsea', 1: '[1.7, 5, 3.8]', 2:'Chelsea', 'AwayOdds' : 5.00, 'HomeOdds' : 1.70, 'DrawOdds':3.8},
      {0:'Cardiff City', 1: '[2.4, 2.8, 3.3]', 2:'Cardiff City', 'AwayOdds' : 1.7, 'HomeOdds' : 5.00, 'DrawOdds':3.8},
      {0:'Newcastle United', 1: '[2.4, 2.8, 3.3]', 2:'Brighton and Hove Albion', 'AwayOdds' : 2.15, 'HomeOdds' : 3.6, 'DrawOdds':3.8}
      ]

In [63]:
d = pd.DataFrame(dict1)

In [64]:
d[[0,1,2,'HomeOdds', 'DrawOdds', 'AwayOdds']]

,0,1,2,HomeOdds,DrawOdds,AwayOdds
0,Chelsea,"[1.7, 5, 3.8]",Chelsea,1.7,3.8,5.00
1,Cardiff City,"[2.4, 2.8, 3.3]",Cardiff City,5.0,3.8,1.70
2,Newcastle United,"[2.4, 2.8, 3.3]",Brighton and Hove Albion,3.6,3.8,2.15

In [74]:
d1=d[[0,1,2,'HomeOdds', 'DrawOdds', 'AwayOdds']].apply(swap,1)

In [75]:
d1[[0,1,2,'HomeOdds', 'DrawOdds', 'AwayOdds']]

,0,1,2,HomeOdds,DrawOdds,AwayOdds
0,Chelsea,"[1.7, 5, 3.8]",Chelsea,1.7,3.8,5
1,Cardiff City,"[2.4, 2.8, 3.3]",Cardiff City,5,3.8,1.7
2,Newcastle United,"[2.4, 2.8, 3.3]",Brighton and Hove Albion,a,b,c